services:
  web:
    build: .
    container_name: LAB-VUL

    ports:
      - "8081:80"

    volumes:
      - ./:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    depends_on:
      - db

    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0.27
    container_name: mysql-lab
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SQL_INJECTION
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
