services:
  web:
    build:
      context: .
    container_name: LAB-VUL
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    container_name: mysql-lab
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SQL_INJECTION
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql